PlatformMutation:
    type: object
    config:
        fields:
            deleteContent:
                type: DeleteContentPayload
                resolve: '@=mutation("DeleteDomainContent", [args])'
                args:
                    id:
                        type: ID
                        description: "Global ID of the content item to delete"
                    contentId:
                        type: Int
                        description: "ID of the content item to delete"
            uploadFiles:
                type: UploadedFilesPayload
                resolve: '@=mutation("UploadFiles", [args])'
                args:
                    locationId:
                        type: Int!
                        description: "The location ID of a container to upload the files to"
                    files:
                        type: "[FileUpload]!"

UploadedFilesPayload:
    type: object
    config:
        fields:
            files:
                type: "[DomainContent]"
            warnings:
                type: "[String]"

DeleteContentPayload:
    type: object
    config:
        fields:
            contentId:
                type: Int
                description: "Numerical content id"
            id:
                type: ID
                description: "Global ID"

ImageFieldInput:
    type: input-object
    config:
        fields:
            name:
                type: String
            alternativeText:
                type: String
            file:
                type: FileUpload

FileUpload:
    type: custom-scalar
    config:
        scalarType: '@=newObject("Overblog\\GraphQLBundle\\Upload\\Type\\GraphQLUploadType")'

RichTextFieldInput:
    type: input-object
    config:
        fields:
            format:
                type: RichTextFieldInputFormat
            input:
                type: String

RichTextFieldInputFormat:
    type: enum
    config:
        values:
            markdown: {}
            html: {}