#Mutation:
#    type: object
#    config:
#        fields:
#            createContent:
#                type: "ContentCreateStruct"
#                args:
#                    struct:
#                        type: "ContentCreateStruct"
#            createContentOld:
#                builder: Mutation
#                builderConfig:
#                    inputType: createContentInput
#                    payloadType: createContentPayload
#                    mutateAndGetPayload: "@=mutation('simple_mutation_with_thunk_fields', [value])"
#
#createContentInput:
#    type: relay-mutation-input
#    config:
#        fields:
#            inputData : { type: "ContentCreateStruct" }
#
#createContentPayload:
#    type: relay-mutation-payload
#    config:
#        fields:
#            result: { type: "Content" }
