services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    _instanceof:
        EzSystems\EzPlatformGraphQL\DomainContent\SchemaWorker\BaseWorker:
            calls:
                - [setNameHelper, ['@EzSystems\EzPlatformGraphQL\DomainContent\NameHelper']]

        EzSystems\EzPlatformGraphQL\DomainContent\SchemaWorker\SchemaWorker:
            tags:
                - {name: 'ezplatform_graphql.domain_schema_worker'}

        EzSystems\EzPlatformGraphQL\Schema\SchemaBuilder:
            tags:
                - {name: 'ezplatform_graphql.schema_builder'}

    EzSystems\EzPlatformGraphQL\DomainContent\DomainContentSchemaBuilder: ~

    EzSystems\EzPlatformGraphQL\Schema\SchemaGenerator: ~

    EzSystems\EzPlatformGraphQL\DomainContent\RepositoryDomainGenerator:

    EzSystems\EzPlatformGraphQL\DomainContent\NameHelper: ~

    EzSystems\EzPlatformGraphQL\DomainContent\SchemaWorker\ContentType\DefineDomainContent: ~

    EzSystems\EzPlatformGraphQL\DomainContent\SchemaWorker\ContentType\AddDomainContentToDomainGroup: ~

    EzSystems\EzPlatformGraphQL\DomainContent\SchemaWorker\ContentTypeGroup\DefineDomainGroup: ~

    EzSystems\EzPlatformGraphQL\DomainContent\SchemaWorker\ContentTypeGroup\AddDomainGroupToDomain: ~

    EzSystems\EzPlatformGraphQL\DomainContent\FieldValueBuilder\BaseFieldValueBuilder: ~

    EzSystems\EzPlatformGraphQL\DomainContent\SchemaWorker\FieldDefinition\AddFieldDefinitionToDomainContent:
        arguments:
            $defaultFieldValueBuilder: '@EzSystems\EzPlatformGraphQL\DomainContent\FieldValueBuilder\BaseFieldValueBuilder'

    EzSystems\EzPlatformGraphQL\DomainContent\SchemaWorker\ContentType\AddContentTypeToContentTypeIdentifierList: ~

    EzSystems\EzPlatformGraphQL\DomainContent\FieldValueBuilder\RelationListFieldValueBuilder:
        tags:
            - {name: ezplatform_graphql.field_value_builder, type: 'ezobjectrelationlist'}

    EzSystems\EzPlatformGraphQL\DomainContent\FieldValueBuilder\SelectionFieldValueBuilder:
        tags:
            - {name: ezplatform_graphql.field_value_builder, type: 'ezselection'}

    EzSystems\EzPlatformGraphQL\Schema\ImagesVariationsBuilder: ~